name: "Check for file changes"

on:
  workflow_call:
    inputs:
      infra_base_sha:
        description: "Base SHA for infrastructure changes"
        required: false
        default: ''
        type: string
      apps_base_sha:
        description: "Base SHA for application changes"
        required: false
        default: ''
        type: string
    outputs:
      hasInfraChanges:
        description: "Infrastructure related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasInfraChanges }}
      hasBackendChanges:
        description: "Backend related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasBackendChanges }}
      hasTestChanges:
        description: "Test related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasTestChanges }}
      hasSlackNotifierChanges:
        description: "Slack Notifier function related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasSlackNotifierChanges }}
      hasSwaggerSchemaChanges:
        description: "Swagger schema has changed"
        value: ${{ jobs.check-for-changes.outputs.hasSwaggerSchemaChanges }}
      hasGqlSchemaChanges:
        description: "GraphQL schema has changed"
        value: ${{ jobs.check-for-changes.outputs.hasGqlSchemaChanges }}
      hasMigrationChanges:
        description: "Migration related files changed"
        value: ${{ jobs.check-for-changes.outputs.hasMigrationChanges }}

jobs:
  check-for-changes:
    name: Filter
    runs-on: ubuntu-latest
    outputs:
      hasInfraChanges: ${{ steps.filter.outputs.azure_any_modified == 'true' }}
      hasSlackNotifierChanges: ${{ steps.filter.outputs.slackNotifier_any_modified == 'true'}}
      hasBackendChanges: ${{ steps.filter-backend.outputs.backend_any_modified == 'true' }}
      hasTestChanges: ${{ steps.filter-backend.outputs.tests_any_modified == 'true' }}
      hasSwaggerSchemaChanges: ${{ steps.filter-backend.outputs.swagger_schema_any_modified == 'true'}}
      hasGqlSchemaChanges: ${{ steps.filter-backend.outputs.gql_schema_any_modified == 'true'}}
      hasMigrationChanges: ${{ steps.filter-backend.outputs.migration_any_modified == 'true'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: tj-actions/changed-files@v45
        id: filter
        with:
          base_sha: ${{ inputs.infra_base_sha }}
          files_yaml: |
            azure:
              - '.github/**/*'
              - '.azure/infrastructure/**/*'
              - '.azure/modules/**/*'
            slackNotifier:
              - '.github/**/*'
              - 'src/Digdir.Tool.Dialogporten.SlackNotifier/**/*'

      - uses: tj-actions/changed-files@v45
        id: filter-backend
        with:
          base_sha: ${{ inputs.apps_base_sha }}
          files_yaml: |
            backend:
              - '.github/**/*'
              - 'src/**/*'
              - '.azure/applications/**/*'
              - '.azure/modules/containerApp/**/*'
            tests:
              - 'tests/**/*'
            swagger_schema:
              - 'docs/schema/V1/swagger.verified.json'
            gql_schema:
              - 'docs/schema/V1/schema.verified.graphql'
            migration: 
              - 'src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/**/*'
